# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20160422_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 22, 20, 53, 59, 637132, tzinfo=utc), verbose_name='Atualizado em'),
            preserve_default=False,
        ),
    ]
